---
driver:
  name: vagrant
  provider: vmware_fusion
  network:
  - ["forwarded_port", {guest: 8082, host: 8082}]
  - ["forwarded_port", {guest: 8083, host: 8083}]
  - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[gravitee::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      gravitee:
        source_url: 'http://192.168.2.7:8888/gravitee/'
